### ISSUE TITLE
Making Omeka Menu coincide with Django Site Menu

### ISSUE THREAD

**Issue by silverli** [HCDigitalScholarship/QI#1]
So... this means that not only should the menu look the same, but also that the home button should go back to the Django site, and other nav-buttons should go back to the Django site too.

I feel like the only part of the nav bar that should link to the Omeka site should be the "Transcriptions" button and that that should go to: https://ds-omeka.haverford.edu/qi/collections/browse/

**Comment by mzarafon** [comment]
Omeka instance is located in /usr/share/nginx/html
Theme files are in /usr/share/nginx/html/qi/themes/scribe/common
