### ISSUE TITLE
Create a 404 and 500 page, turn off Debug mode

### ISSUE THREAD

**Issue by mzarafon** [HCDigitalScholarship/QI#18]
A tutorial for how to do this is here: https://github.com/HCDigitalScholarship/documentation/blob/master/django404.md

**Comment by TA2018** [comment]
the 404 page is working, but not sure about how to check if the 500 page is working and debug mode is turned off

**Comment by zhanpengwang888** [comment]
I have added the necessary code for 500 page to the view.py and turned off the Debug mode in the setting.py.
