### ISSUE TITLE
Make a MongoDB/Django 1.8 Project

### ISSUE THREAD

**Issue by silverli** [HCDigitalScholarship/QI#2]
This seems to be a bit difficult.  There is definitely built-in support for making django 1.5 work with mongo db, but later than that version seems to be unsupported.  I have been trying to follow this tutorial with little luck: 
http://petrkout.com/programming/setting-up-django-with-mongodb/

Here is some additionaly documentation too:
https://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/
http://petrkout.com/linux/installing-mongodb-2-6-and-setting-up-root-user-login/

**Comment by librlaurie** [comment]
We've decided against using mongodb here. Django handles database stuff.
