### ISSUE TITLE
Make submenus of collapsible navbar on omeka site open like those on the django site

### ISSUE THREAD

**Issue by TA2018** [HCDigitalScholarship/QI#22]
Instead of looking like this: 
![screen shot 2017-02-13 at 2 50 13 pm](https://cloud.githubusercontent.com/assets/12700689/22900294/d436cfd6-f1fb-11e6-8229-d0ec8ee258ec.png)

it should look like this:
![screen shot 2017-02-13 at 2 50 31 pm](https://cloud.githubusercontent.com/assets/12700689/22900306/e48569ce-f1fb-11e6-8ee8-2b69780a4255.png)

**Comment by mzarafon** [comment]
Omeka site is no longer part of the project now that the transcriber is a Django app
