### ISSUE TITLE
Links from Overview Maps to Travelers are broken (404 error)

### ISSUE THREAD

**Issue by mzarafon** [HCDigitalScholarship/QI#26]
![screen shot 2017-02-22 at 10 06 22 am](https://cloud.githubusercontent.com/assets/6663159/23217238/9707b7c8-f8e6-11e6-99ff-46746e7e700b.png)

Link to traveler from info window on this map goes to a nonexistant link. For example, the link in the screenshot above goes to https://pennstreaty.haverford.edu/manuscript/WilliamHartshorne_1793/ but this does not follow the naming conventions for our manuscripts. This might be a Carto fix.

**Comment by beckylytle** [comment]
I fixed this issue on carto (added a column for manuscript id, changed the html in the popup windows when you click on a dot) -- now just have to fix the actual html/js of the django template somehow to update from carto
