### ISSUE TITLE
Fix absolute/relative positioned CSS for slideouts template in about.html

### ISSUE THREAD

**Issue by silverli** [HCDigitalScholarship/QI#9]
I didn't understand the distinction between absolute and relatively positioned things that well when I was doing this, and it should probably be fixed at some point.  

From what I understand now, you should have the parent element relatively positioned, and whatever will be positioned inside it--the child-- should be absolutely positioned.

**Comment by mzarafon** [comment]
Sliders are gone in favor of popovers now
